[package]
name = "remoteprocess"
version = "0.4.0"
authors = ["Ben Frederickson <github@benfrederickson.com>"]
repository = "https://github.com/benfred/remoteprocess"
homepage = "https://github.com/benfred/remoteprocess"
description = "cross platform api for getting information on a running processes"
readme = "README.md"
license = "MIT"
build="build.rs"

[dependencies]
libc = "0.2"
log = "0.4"
proc-maps = "0.1.6"
benfred-read-process-memory = "0.2.0"
goblin = "0.1.3"
memmap = "0.7.0"
lazy_static = "1.1.0"
regex = "1"

[target.'cfg(target_os="macos")'.dependencies]
mach_o_sys = "0.1.1"
mach = "0.3.2"
libproc = "0.7"

[target.'cfg(target_os="linux")'.dependencies]
nix="0.17"
object = "0.17"
addr2line = "0.11"

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3", features = ["winbase", "consoleapi", "wincon", "handleapi", "timeapi", "processenv" ]}

[dev-dependencies]
env_logger = "0.7"

[features]
default = []
unwind = []
